language: php

php:
- 5.6
- 5.5
- 5.4

env:
- NO_INTERACTION=1

compiler:
- gcc

install:
- sudo apt-get update -qq
- sudo apt-get install -qq php5-dev

script:
- phpize
- ./configure
- make
- make test
